NDefines.NMilitary.CAROLEAN_STARTING_STRENGTH = 1.0
NDefines.NMilitary.CAROLEAN_STARTING_MORALE = 0.1
NDefines.NMilitary.CAROLEAN_USES_CONSTRUCTION = 0
NDefines.NMilitary.CAROLEAN_BASE_COST_MODIFIER = 2.0